# Generated by Django 3.1.4 on 2021-03-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Film',
        ),
    ]
